/home/gxmg/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1424: RuntimeWarning: DateTimeField Reservation.start_date received a naive datetime (2020-09-01 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
/home/gxmg/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1424: RuntimeWarning: DateTimeField Reservation.start_date received a naive datetime (2020-09-14 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
/home/gxmg/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1424: RuntimeWarning: DateTimeField Reservation.start_date received a naive datetime (2020-09-15 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
Performing system checks...

System check identified no issues (0 silenced).
September 15, 2020 - 11:12:23
Django version 2.2.14, using settings 'radeclaRest.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
receiver called
2020-09-15 17:00:00+00:00
2020-09-15 12:00:00+00:00
receiver called
2020-09-15 17:00:00+00:00
2020-09-15 12:00:00+00:00
receiver called
2020-09-15 17:00:00+00:00
2020-09-15 12:00:00+00:00
receiver called
2020-09-15 17:00:00+00:00
2020-09-15 12:00:00+00:00
receiver called
2020-09-15 17:00:00+00:00
2020-09-15 12:00:00+00:00
receiver called
2020-09-15 17:00:00+00:00
2020-09-15 12:00:00+00:00
System check identified some issues:

WARNINGS:
core.Membre.categorie: (fields.W340) null has no effect on ManyToManyField.

System check identified 1 issue (0 silenced).
